name: techie_ai
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  http: ^1.2.2
  google_generative_ai: ^0.4.3
  flutter_dotenv: ^5.1.0
  font_awesome_flutter: ^10.1.0

  animated_text_kit: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  assets:
    - .env
    - assets/gaming_pc.png
    - assets/office_pc.png
    - assets/personal_pc.png
    - assets/loading1.png
    - assets/loading2.png
    - assets/loading3.png
    # - assets/images/logo.png