name: techie_ai
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  http: ^1.2.2
  google_generative_ai: ^0.4.3
  flutter_dotenv: ^5.1.0
  font_awesome_flutter: ^10.1.0
  animated_text_kit: ^4.2.1
  pdf: ^3.8.0
  printing: ^5.10.0
  google_fonts: ^6.2.1
  url_launcher: ^6.0.20
  google_sign_in: ^5.2.3
  shared_preferences: ^2.0.15
  googleapis: ^3.0.0
  googleapis_auth: ^1.2.0
  flutter_web_auth: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  assets:
    - .env
    - assets/gaming_pc.png
    - assets/office_pc.png
    - assets/personal_pc.png
    - assets/loading1.png
    - assets/loading2.png
    - assets/loading3.png
    - assets/logo.png
    - assets/icons/app_icon_48.png
    - assets/icons/app_icon_128.png
    - assets/icons/app_icon_256.png
    - assets/background.webp
    - assets/photo.jpg
